
# Site
title:              Bill's Tech Blog
bio:                'Code To Death'
description:        "To Be Excellent"
locale:             en_cn
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sunbingfeng.github.io" # the base hostname & protocol for your site


defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   sunbingfeng-github-io

# Social
analytics-id:       UA-147107754-1
github:             sunbingfeng
twitter:            sunbingfeng2
facebook:           sun.bill.3
instagram:          default


# personal
location:           Shenzhen, China
# phone:              310-318-5555
email:              bingfeng.sun@perceptin.io

# This will require each of these plugins automatically.
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

emoji:
  src: "https://github.githubassets.com/images/icons/"
  
paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]

theme: jekyll-theme-cayman